---
disabled_rules:
  - closure_parameter_position
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - type_body_length
  - type_name
  - nesting
  - colon
included:
  - MuuvTest
line_length: 120
opt_in_rules:
  - empty_count
  - private_outlet
  - sorted_imports
